Adding support viatable w tests
notamedia/yii2-relation pull request #13
Opened 2016-10-20 12:47 UTC by nixmen

2016-12-06 14:58 UTC, lithium-li commented on RelationBehavior.php
> +            $data['oldModels'] = [];
its missed in PhpDoc

2016-12-12 20:37 UTC, senor-artemisio requested changes
In general, everything is fine, but you need to solve the problem with on condition

2016-12-12 20:37 UTC, lithium-li commented on README.md
> +                ->viaTable('table_many_to_many', ['entity_id' => 'id']);
missing example with on condition for join with table_many_to_many table

2016-12-12 20:37 UTC, lithium-li commented on README.md
> +                ->viaTable('table_many_to_many', ['entity_id' => 'id']);
I use such relation


```php
<?php
return $this->hasMany(Woo::className(), ['id' => 'woo_id'])
   ->viaTable(WooRelation::tableName(), ['item_id' => 'id'], function ($query) {
     /** @var ActiveQuery $query */
     return $query->onCondition(['item_type' => 'woo']);
   }
);
```

and it's didn't work fine - old tags removes after save, remains only new tags.

If problem in RelationBehavior, you shoud fix it, else just add correct example that will works.

2016-12-12 20:37 UTC, lithium-li commented on tests/unit/FakeNewsModel.php
> +            ['news_id' => 'id']);
missing test with on condition

2016-12-13 09:30 UTC, nixmen commented on README.md
> +                ->viaTable('table_many_to_many', ['entity_id' => 'id']);
fixed

2016-12-13 11:22 UTC, nixmen commented on tests/unit/FakeNewsModel.php
> +            ['news_id' => 'id']);
add

2016-12-13 18:46 UTC, senor-artemisio requested changes
![1481692930647](https://cloud.githubusercontent.com/assets/1178789/21170471/d381a6a8-c1de-11e6-8070-238b948c51d6.jpg)

 why file names is duplicated?

2016-12-13 18:46 UTC, lithium-li commented on tests/unit/RelationBehaviorTest.php
> +        die('end');
WTF?!

2016-12-13 18:46 UTC, lithium-li commented on tests/unit/FakeNewsModel.php
>   * Тестовая модель Новости
it's should be translated to English

2016-12-13 18:46 UTC, lithium-li commented on tests/unit/FakeNewsModel.php
>       * @return $this
wrong PHPDoc

2016-12-14 05:29 UTC, nixmen commented on tests/unit/FakeNewsModel.php
>       * @return $this
fixed

2016-12-14 05:29 UTC, nixmen commented on tests/unit/FakeNewsModel.php
>   * Тестовая модель Новости
translated

2016-12-14 05:29 UTC, nixmen commented on tests/unit/RelationBehaviorTest.php
> +        die('end');
fixed

2017-02-16 14:13 UTC, closed without merging