Callback preprocessing
notamedia/yii2-relation pull request #17
Opened 2017-07-12 07:52 UTC by wirelesszero

- Added callback preprocessing
- Changed README
- Change save -> delete order of related models to delete -> save

2017-07-26 15:20 UTC, niksamokhvalov requested changes
Неплохо.

2017-07-26 15:20 UTC, niksamokhvalov commented on RelationBehavior.php
> +    protected $relationalFields = [];
Нельзя ломать обратную совместимость.

2017-07-26 15:20 UTC, niksamokhvalov commented on RelationBehavior.php
> +    public function init()
Кажется ты забыл про `parent::init()`.

2017-07-26 15:20 UTC, niksamokhvalov commented on tests/_support/_generated/UnitTesterActions.php
> +<?php  //[STAMP] b6dd4c08ea50a64e655eda981ed153de
А зачем нам generated-файлы в гите?..

2017-07-31 14:14 UTC, wirelesszero commented on RelationBehavior.php
> +    public function init()
Done.

2017-08-01 09:34 UTC, merged